Correct Missing Type Annotations
adafruit/Adafruit_CircuitPython_SHT4x pull request #10
Opened 2022-08-20 17:56 UTC by tcfranks

2022-08-20 18:09 UTC, tcfranks commented
ready for review / comments

2022-08-22 17:03 UTC, tekktrik commented
I can take a look at this tonight, but see other libraries that use the `CV` class implementation for help on type annotating this:  https://github.com/adafruit/Adafruit_CircuitPython_TLA202x/blob/aa66231e5f90c6e33acce4cc3888bd888fed9e92/adafruit_tla202x/__init__.py

2022-08-22 22:25 UTC, tekktrik requested changes
Everything looks good so far!  I provided a link for help with type annotating the remaining parts.

2022-08-22 22:25 UTC, tekktrik commented on adafruit_sht4x.py
> +    def add_values(cls, value_tuples) -> None:
See https://github.com/adafruit/Adafruit_CircuitPython_TLA202x/blob/main/adafruit_tla202x/__init__.py for help annotating `CV.add_values()`, as they work identically.

2022-08-22 22:25 UTC, tekktrik commented on adafruit_sht4x.py
> +    def is_valid(cls, value) -> bool:
See https://github.com/adafruit/Adafruit_CircuitPython_TLA202x/blob/main/adafruit_tla202x/__init__.py for help annotating `CV.is_valid()`, as they work identically.

2022-08-23 00:03 UTC, tcfranks commented
ready for re-review

2022-08-23 01:14 UTC, tekktrik requested changes
Thanks for adding the remaining things!  It looks like the base material was a little off or could be made slightly more specific here so a few changes for that.

2022-08-23 01:14 UTC, tekktrik commented on adafruit_sht4x.py
> +        cls, value_tuples: Tuple[str, int, Union[float, str], Optional[float]]
In this instance, it looks like it's `Tuple[str, int, str, float]`

2022-08-23 01:14 UTC, tekktrik commented on adafruit_sht4x.py
> +    def is_valid(cls, value: str) -> bool:
Looks like the base material I gave you was wrong, `value` should be `int`

2022-08-23 13:34 UTC, tekktrik approved these changes
Thanks!

2022-08-23 13:34 UTC, merged

2022-08-23 13:34 UTC, tcfranks commented
review for prev comments