allow change i2c address
adafruit/Adafruit_CircuitPython_SHT4x pull request #3
Opened 2021-02-26 10:37 UTC by MkLHX

Hello, like bme280
https://github.com/adafruit/Adafruit_CircuitPython_BME280/blob/287979991b5b69f01315bf17e18fddeb48cc6b3b/adafruit_bme280.py#L470
it would be greate to allow changing i2c address when instance is created.

2021-02-26 19:45 UTC, tannewt requested changes
Thank you for the PR! Please change the variable name to match the BME280 example (and hopefully other libraries.)

2021-02-26 19:45 UTC, tannewt commented on adafruit_sht4x.py
> +        self.i2c_device = i2c_device.I2CDevice(i2c_bus, i2c_addr)
```suggestion
    def __init__(self, i2c_bus, address=_SHT4X_DEFAULT_ADDR):
        self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
```

2021-03-01 15:55 UTC, MkLHX commented on adafruit_sht4x.py
> +        self.i2c_device = i2c_device.I2CDevice(i2c_bus, i2c_addr)
Hi @tannewt, i did it

2021-03-01 16:05 UTC, ladyada approved these changes

2021-03-01 16:05 UTC, merged